executable = /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/XXXX/$(dir)/cfg_analyzer.sh
use_x509userproxy = true
GetEnv = True
arguments = $(ClusterId) $(ProcId) \"$(dir)\"
output = /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/XXXX/$(dir)/out
error =  /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/XXXX/$(dir)/err
log =    /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/XXXX/condor.log
+MaxRuntime = 7200
+JobBatchName = "TOTEM2_1"


dir=dir_0000
queue

dir=dir_0001
queue

dir=dir_0002
queue

dir=dir_0003
queue

dir=dir_0004
queue

dir=dir_0005
queue

dir=dir_0006
queue

dir=dir_0007
queue

dir=dir_0008
queue

dir=dir_0009
queue

dir=dir_0010
queue

dir=dir_0011
queue

dir=dir_0012
queue

dir=dir_0013
queue

dir=dir_0014
queue

dir=dir_0015
queue

dir=dir_0016
queue

dir=dir_0017
queue

dir=dir_0018
queue

dir=dir_0019
queue

dir=dir_0020
queue

dir=dir_0021
queue

dir=dir_0022
queue

dir=dir_0023
queue

dir=dir_0024
queue

dir=dir_0025
queue

dir=dir_0026
queue

dir=dir_0027
queue

dir=dir_0028
queue

dir=dir_0029
queue

dir=dir_0030
queue

dir=dir_0031
queue

dir=dir_0032
queue

dir=dir_0033
queue

dir=dir_0034
queue

dir=dir_0035
queue

dir=dir_0036
queue

dir=dir_0037
queue

dir=dir_0038
queue

dir=dir_0039
queue

