executable = /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/XXXX/$(dir)/cfg_analyzer.sh
use_x509userproxy = true
GetEnv = True
arguments = $(ClusterId) $(ProcId) \"$(dir)\"
output = /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/XXXX/$(dir)/out
error =  /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/XXXX/$(dir)/err
log =    /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/XXXX/condor.log
+MaxRuntime = 7200
+JobBatchName = "TOTEM2_1"


dir=dir_0040
queue

dir=dir_0041
queue

dir=dir_0042
queue

dir=dir_0043
queue

dir=dir_0044
queue

dir=dir_0045
queue

dir=dir_0046
queue

dir=dir_0047
queue

dir=dir_0048
queue

dir=dir_0049
queue

dir=dir_0050
queue

dir=dir_0051
queue

dir=dir_0052
queue

dir=dir_0053
queue

dir=dir_0054
queue

dir=dir_0055
queue

dir=dir_0056
queue

dir=dir_0057
queue

dir=dir_0058
queue

dir=dir_0059
queue

dir=dir_0060
queue

dir=dir_0061
queue

dir=dir_0062
queue

dir=dir_0063
queue

dir=dir_0064
queue

dir=dir_0065
queue

dir=dir_0066
queue

dir=dir_0067
queue

dir=dir_0068
queue

dir=dir_0069
queue

dir=dir_0070
queue

dir=dir_0071
queue

dir=dir_0072
queue

dir=dir_0073
queue

dir=dir_0074
queue

dir=dir_0075
queue

dir=dir_0076
queue

dir=dir_0077
queue

dir=dir_0078
queue

dir=dir_0079
queue

