executable = /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_11_m/Elastic_analysis/Project_files/Fill_7301/Monte_Carlo/Condor/MC_with_beam_divergence_exp_hor/$(dir)/cfg_analyzer.sh
use_x509userproxy = true
GetEnv = True
arguments = $(ClusterId) $(ProcId) \"$(dir)\"
output = /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_11_m/Elastic_analysis/Project_files/Fill_7301/Monte_Carlo/Condor/MC_with_beam_divergence_exp_hor/$(dir)/out
error =  /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_11_m/Elastic_analysis/Project_files/Fill_7301/Monte_Carlo/Condor/MC_with_beam_divergence_exp_hor/$(dir)/err
log =    /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_11_m/Elastic_analysis/Project_files/Fill_7301/Monte_Carlo/Condor/MC_with_beam_divergence_exp_hor/condor.log
+MaxRuntime = 7200
+JobBatchName = "TOTEM2_1"


dir=dir_0000 
queue

dir=dir_0001 
queue

dir=dir_0002 
queue

dir=dir_0003 
queue

dir=dir_0004 
queue

dir=dir_0005 
queue

dir=dir_0006 
queue

dir=dir_0007 
queue

dir=dir_0008 
queue

dir=dir_0009 
queue

dir=dir_0010 
queue

dir=dir_0011 
queue

dir=dir_0012 
queue

dir=dir_0013 
queue

dir=dir_0014 
queue

dir=dir_0015 
queue

dir=dir_0016 
queue

dir=dir_0017 
queue

dir=dir_0018 
queue

dir=dir_0019 
queue

dir=dir_0020 
queue

dir=dir_0021 
queue

dir=dir_0022 
queue

dir=dir_0023 
queue

dir=dir_0024 
queue

dir=dir_0025 
queue

dir=dir_0026 
queue

dir=dir_0027 
queue

dir=dir_0028 
queue

dir=dir_0029 
queue

dir=dir_0030 
queue

dir=dir_0031 
queue

dir=dir_0032 
queue

dir=dir_0033 
queue

dir=dir_0034 
queue

dir=dir_0035 
queue

dir=dir_0036 
queue

dir=dir_0037 
queue

dir=dir_0038 
queue

dir=dir_0039 
queue

dir=dir_0040 
queue

dir=dir_0041 
queue

dir=dir_0042 
queue

dir=dir_0043 
queue

dir=dir_0044 
queue

dir=dir_0045 
queue

dir=dir_0046 
queue

dir=dir_0047 
queue

dir=dir_0048 
queue

dir=dir_0049 
queue

dir=dir_0050 
queue

dir=dir_0051 
queue

dir=dir_0052 
queue

dir=dir_0053 
queue

dir=dir_0054 
queue

dir=dir_0055 
queue

dir=dir_0056 
queue

dir=dir_0057 
queue

dir=dir_0058 
queue

dir=dir_0059 
queue

dir=dir_0060 
queue

dir=dir_0061 
queue

dir=dir_0062 
queue

dir=dir_0063 
queue

dir=dir_0064 
queue

dir=dir_0065 
queue

dir=dir_0066 
queue

dir=dir_0067 
queue

dir=dir_0068 
queue

dir=dir_0069 
queue

dir=dir_0070 
queue

dir=dir_0071 
queue

dir=dir_0072 
queue

dir=dir_0073 
queue

dir=dir_0074 
queue

dir=dir_0075 
queue

dir=dir_0076 
queue

dir=dir_0077 
queue

dir=dir_0078 
queue

dir=dir_0079 
queue

dir=dir_0080 
queue

dir=dir_0081 
queue

dir=dir_0082 
queue

dir=dir_0083 
queue

dir=dir_0084 
queue

dir=dir_0085 
queue

dir=dir_0086 
queue

dir=dir_0087 
queue

dir=dir_0088 
queue

dir=dir_0089 
queue

dir=dir_0090 
queue

dir=dir_0091 
queue

dir=dir_0092 
queue

dir=dir_0093 
queue

dir=dir_0094 
queue

dir=dir_0095 
queue

dir=dir_0096 
queue

dir=dir_0097 
queue

dir=dir_0098 
queue

dir=dir_0099 
queue

