condor_submit tmp/ok_aa.sub
condor_submit tmp/ok_ab.sub
condor_submit tmp/ok_ac.sub
condor_submit tmp/ok_ad.sub
condor_submit tmp/ok_ae.sub
condor_submit tmp/ok_af.sub
condor_submit tmp/ok_ag.sub
condor_submit tmp/ok_ah.sub
condor_submit tmp/ok_ai.sub
condor_submit tmp/ok_aj.sub
