./analyse Projects/2023/E_CM_900_GeV_beta_star_11_m/Elastic_analysis/Project_files/Fill_7301/Left_bottom_right_top_4_sigma_all_root_files_to_define_cuts_aligned_first_optics_test.prj /dev/null &
./analyse Projects/2023/E_CM_900_GeV_beta_star_11_m/Elastic_analysis/Project_files/Fill_7302/Left_bottom_right_top_4_sigma_all_root_files_to_define_cuts_aligned_first_optics_test.prj /dev/null &
./analyse Projects/2023/E_CM_900_GeV_beta_star_11_m/Elastic_analysis/Project_files/Fill_7301/Left_top_right_bottom_4_sigma_all_root_files_to_define_cuts_aligned_first_optics_test.prj /dev/null &
./analyse Projects/2023/E_CM_900_GeV_beta_star_11_m/Elastic_analysis/Project_files/Fill_7302/Left_top_right_bottom_4_sigma_all_root_files_to_define_cuts_aligned_first_optics_test.prj /dev/null &
