echo
echo "Most basic reference truth without acceptance cuts compared to real MC WITH acceptance cuts"
diff Left_bottom_right_top_4_sigma_all_root_files_to_define_cuts_aligned_first_optics_test_hor_cor_reference.prj Left_bottom_right_top_4_sigma_all_root_files_to_define_cuts_aligned_first_optics_test_hor_cor.prj

echo
echo
echo "Two reference MC truth are compared with and without beam divergence"
diff  Left_bottom_right_top_4_sigma_all_root_files_to_define_cuts_aligned_first_optics_test_hor_cor_reference.prj Left_bottom_right_top_4_sigma_all_root_files_to_define_cuts_aligned_first_optics_test_hor_cor_reference_with_beam_divergence.prj


echo
echo
echo "Two real MC are compared with and without beam divergence"
diff Left_bottom_right_top_4_sigma_all_root_files_to_define_cuts_aligned_first_optics_test_hor_cor_with_beam_divergence.prj  Left_bottom_right_top_4_sigma_all_root_files_to_define_cuts_aligned_first_optics_test_hor_cor.prj


echo
echo
echo "The MC truth with beam divergence is compared to MC real"
diff Left_bottom_right_top_4_sigma_all_root_files_to_define_cuts_aligned_first_optics_test_hor_cor_reference_with_beam_divergence.prj Left_bottom_right_top_4_sigma_all_root_files_to_define_cuts_aligned_first_optics_test_hor_cor_with_beam_divergence.prj

echo
echo
echo "Two MCs with same beam divergence but different acceptance cuts, to test stronger cut effects and beam div. corrections"
diff Left_bottom_right_top_4_sigma_all_root_files_to_define_cuts_aligned_first_optics_test_hor_cor_with_beam_divergence_stronger_cuts_for_test.prj Left_bottom_right_top_4_sigma_all_root_files_to_define_cuts_aligned_first_optics_test_hor_cor_with_beam_divergence.prj
