executable = /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/MC_ver/$(dir)/cfg_analyzer.sh
use_x509userproxy = true
GetEnv = True
arguments = $(ClusterId) $(ProcId) \"$(dir)\"
output = /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/MC_ver/$(dir)/out
error =  /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/MC_ver/$(dir)/err
log =    /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/MC_ver/condor.log
+MaxRuntime = 7200
+JobBatchName = "TOTEM2_1"


dir=dir_0280
queue

dir=dir_0281
queue

dir=dir_0282
queue

dir=dir_0283
queue

dir=dir_0284
queue

dir=dir_0285
queue

dir=dir_0286
queue

dir=dir_0287
queue

dir=dir_0288
queue

dir=dir_0289
queue

dir=dir_0290
queue

dir=dir_0291
queue

dir=dir_0292
queue

dir=dir_0293
queue

dir=dir_0294
queue

dir=dir_0295
queue

dir=dir_0296
queue

dir=dir_0297
queue

dir=dir_0298
queue

dir=dir_0299
queue

dir=dir_0300
queue

dir=dir_0301
queue

dir=dir_0302
queue

dir=dir_0303
queue

dir=dir_0304
queue

dir=dir_0305
queue

dir=dir_0306
queue

dir=dir_0307
queue

dir=dir_0308
queue

dir=dir_0309
queue

dir=dir_0310
queue

dir=dir_0311
queue

dir=dir_0312
queue

dir=dir_0313
queue

dir=dir_0314
queue

dir=dir_0315
queue

dir=dir_0316
queue

dir=dir_0317
queue

dir=dir_0318
queue

dir=dir_0319
queue

