executable = /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/XXXX/$(dir)/cfg_analyzer.sh
use_x509userproxy = true
GetEnv = True
arguments = $(ClusterId) $(ProcId) \"$(dir)\"
output = /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/XXXX/$(dir)/out
error =  /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/XXXX/$(dir)/err
log =    /afs/cern.ch/work/f/fnemes/main_workspace_github_ssh_4/Projects/TOTEM_Projects/Physics_projects/Physics_analysis/Proton_proton_scattering/Elastic_scattering/Projects/2023/E_CM_900_GeV_beta_star_100_m/Elastic_analysis/Studies/Monte_Carlo/Condor/XXXX/condor.log
+MaxRuntime = 7200
+JobBatchName = "TOTEM2_1"


dir=dir_0320
queue

dir=dir_0321
queue

dir=dir_0322
queue

dir=dir_0323
queue

dir=dir_0324
queue

dir=dir_0325
queue

dir=dir_0326
queue

dir=dir_0327
queue

dir=dir_0328
queue

dir=dir_0329
queue

dir=dir_0330
queue

dir=dir_0331
queue

dir=dir_0332
queue

dir=dir_0333
queue

dir=dir_0334
queue

dir=dir_0335
queue

dir=dir_0336
queue

dir=dir_0337
queue

dir=dir_0338
queue

dir=dir_0339
queue

